name-template: "v$RESOLVED_VERSION 🌈"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: "Bug Fixes"
    label: "bug"
  - title: "New Features"
    label: "feature"
  - title: "Documentation"
    label: "documentation"
  - title: "Chore"
    label: "chore"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
template: |
  ## Changes

  $CHANGES
